# **Pengantar Data Sains | 23 Februari 2026**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(42)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
data = {
    'year': [
        2010, 2011, 2012,
        2010, 2011, 2012,
        2010, 2011, 2012,
    ],
    'team': [
        'FCBarcelona', 'FCBarcelona', 'FCBarcelona',
        'RMadrid', 'RMadrid', 'RMadrid',
        'ValenciaCF', 'ValenciaCF', 'ValenciaCF'
    ],
    'wins': [30, 28, 32, 29, 32, 26, 21, 17, 19],
    'draws': [6, 7, 4, 5, 4, 7, 8, 10, 8],
    'losses': [2, 3, 2, 4, 2, 5, 9, 11, 11],
}

football = pd.DataFrame(data, columns=['year', 'team', 'wins', 'draws', 'losses'])
football

   year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3
2  2012  FCBarcelona    32      4       2
3  2010      RMadrid    29      5       4
4  2011      RMadrid    32      4       2
5  2012      RMadrid    26      7       5
6  2010   ValenciaCF    21      8       9
7  2011   ValenciaCF    17     10      11
8  2012   ValenciaCF    19      8      11

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Students_Performance_knn.csv")
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,NaN,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [ ]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
df.loc[7:12, ['lunch', 'math score']]

           lunch  math score
7   free/reduced          40
8   free/reduced          64
9   free/reduced          38
10      standard          58
11      standard          40
12      standard          65

In [ ]:
df.iloc[7:14, 2:5]

   parental level of education         lunch test preparation course
7                 some college  free/reduced                    none
8                  high school  free/reduced               completed
9                  high school  free/reduced                    none
10          associate's degree      standard                    none
11          associate's degree      standard                    none
12                 high school      standard                    none
13                some college      standard               completed

In [ ]:
df[df['math score']>92]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
34,male,group E,some college,standard,none,97,87,82
104,male,group C,some college,standard,completed,98,86,90
114,female,group E,bachelor's degree,standard,completed,99,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93
165,female,group C,bachelor's degree,standard,completed,96,100,100
171,male,group E,some high school,standard,none,94,88,78
179,female,group D,some high school,standard,completed,97,100,100
263,female,group E,high school,standard,none,99,93,90
286,male,group E,associate's degree,standard,completed,97,82,88
306,male,group E,some college,NaN,completed,99,87,81
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
501,female,group B,associate's degree,standard,completed,94,87,92
503,female,group E,associate's degree,standard,completed,95,89,92
539,male,group A,associate's degree,standard,completed,97,92,86
562,male,group C,bachelor's degree,standard,completed,96,90,92
612,male,group C,bachelor's degree,standard,completed,94,90,91
618,male,group D,master's degree,standard,none,95,81,84
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
685,female,group E,master's degree,standard,completed,94,99,100
689,male,group E,some college,free/reduced,none,93,90,83
710,male,group C,some college,standard,completed,93,84,90
712,female,group D,some college,standard,none,98,100,99
717,female,group C,associate's degree,standard,completed,96,96,99
779,male,group E,associate's degree,standard,completed,94,85,82
815,male,group B,some high school,standard,completed,94,86,87
855,female,group B,bachelor's degree,standard,none,97,97,96
864,male,group C,associate's degree,standard,none,97,93,91
886,female,group E,associate's degree,standard,completed,93,100,95
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
934,male,group C,associate's degree,standard,completed,98,87,90
950,male,group E,high school,standard,none,94,73,71
962,female,group E,associate's degree,standard,none,100,100,100

In [ ]:
df.isnull().sum()

gender                          0
race/ethnicity                  0
parental level of education     0
lunch                          25
test preparation course         0
math score                      0
reading score                   0
writing score                   0
dtype: int64

In [ ]:
df.count()

gender                         1000
race/ethnicity                 1000
parental level of education    1000
lunch                           975
test preparation course        1000
math score                     1000
reading score                  1000
writing score                  1000
dtype: int64

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool